[server]
host = "127.0.0.1"
port = 8000

[proxy]
scheme = "http"

  [proxy.auth]
  # Enable/Disable auth.
  auth = true

  # Do not commit tokens/keys in the code.
  # IMPORTANT: jwt tokens are credentials.
  # NOTE: spaces and new line characters will be trimmed.
  # For local development please use config/local.toml.
  alg = "RS256"
  rsa_modulus ='''
  PLACE_MODULUS_HERE
  '''
  rsa_exponent = "PLACE_EXPONENT_HERE"

  [[proxy.hosts]]
  path = "/"
  host = "localhost:3000"
