[server]
host = "127.0.0.1"
port = 8000

[proxy]
scheme = "http"
x_forwarded_for = true
x_forwarded_proto = true

  [[proxy.hosts]]
  path = "/"
  host = "localhost:3000"

  [[proxy.hosts]]
  path = "/test"
  host = "localhost:4000"

